[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]

[dev-dependencies]
insta = "1.42.0"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3