[package]
name = "froql"
version = "0.1.0"
edition = "2024"

[dependencies]
hi_sparse_bitset = "0.6.1"
froql_macro = { version = "0.1.0", path = "../froql_macro" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
