name: Miri

on: [push, pull_request]

jobs:
  test:
    name: cargo miri
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: |
         rustup toolchain install nightly --profile minimal --no-self-update
         rustup +nightly component add miri
         curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - uses: Swatinem/rust-cache@v2

      - run: |
          cargo +nightly miri nextest run -j12
